package com.gci.siarp.api.ui.crud;

import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.validator.BeanValidator;
import com.vaadin.ui.AbstractTextField;
import com.vaadin.ui.ComponentContainer;
import com.vaadin.ui.Field;

/**
 * 
 * @author Alejandro
 *
 */
public class AutoGeneratedCrudFormHelper {

	public static void addFields(Class<?> domainObjectClass, Object[] visiblePropertyIds, Object disabledPropertyIds[], String[] fieldCaptions, boolean readOnly, FieldGroup fieldGroup, ComponentContainer mainLayout) {

		for (int i = 0; i < visiblePropertyIds.length; i++) {
			Object propertyId = visiblePropertyIds[i];
			Field<?> field = fieldGroup.buildAndBind(propertyId);
			field.setReadOnly(readOnly);
			field.addValidator(new BeanValidator(domainObjectClass, "" + propertyId));

			if (fieldCaptions != null) {
				field.setCaption(fieldCaptions[i]);
			}

			if (AbstractTextField.class.isAssignableFrom(field.getClass())) {
				((AbstractTextField) field).setNullRepresentation("");
			}

			mainLayout.addComponent(field);
		}

		if (disabledPropertyIds != null) {
			for (int i = 0; i < disabledPropertyIds.length; i++) {
				fieldGroup.getField(disabledPropertyIds[i]).setEnabled(false);
			}
		}

	}

}
