package com.gci.siarp.macropartes.domain;

import java.util.Collection;

import com.gci.siarp.api.ui.SiarpTheme;
import com.gci.siarp.macropartes.service.MacropartesService;
import com.gci.siarp.macropartes.ui.ReportARS;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.server.FontAwesome;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

public class buscarArs extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private Table table_1;
	@AutoGenerated
	private Panel panel_3;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button bt_buscar;
	@AutoGenerated
	private TextField tf_buscarArs;
	@AutoGenerated
	private Label label_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	private BeanItemContainer<Ars> beanConNotificacionesPendientes;
	private Collection<Ars> listTipoNotificacionPendientes;
	private MacropartesService macropartesService;
	public buscarArs(MacropartesService macropartesService) {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		stylos();
		this.macropartesService = macropartesService;
		beanConNotificacionesPendientes = new BeanItemContainer<Ars>(Ars.class);
		table_1.addStyleName(SiarpTheme.TABLE_BLUE_HEADER);
		table_1.setContainerDataSource(beanConNotificacionesPendientes);
		table_1.addGeneratedColumn("Acciones", this::accionesReferencias);
		table_1.setVisibleColumns("Acciones","fechaServicio", "ncom","ciudad","serviteca","unidad","recibe","sigla");
		table_1.setColumnHeaders("Detalle", "Fecha Servicio", "Num. Comprobante", "Ciudad", "Serviteca", "Unidad", "Recibe", "Sigla");
		// TODO add user code here
		bt_buscar.addClickListener(e->buscaArs());
		
	}
	
	private void stylos(){
		panel_3.addStyleName(SiarpTheme.PANEL_HEADER_BLUE);
		bt_buscar.setIcon(FontAwesome.SEARCH);
		bt_buscar.addStyleName(SiarpTheme.BUTTON_PRIMARY);
	}
	
	private void buscaArs() {
		listTipoNotificacionPendientes = macropartesService.buscarArs("%"+tf_buscarArs.getValue()+"%");
		beanConNotificacionesPendientes.removeAllItems();
		beanConNotificacionesPendientes.addAll(listTipoNotificacionPendientes);
	}

	
	public Object accionesReferencias(Table source, Object itemId, Object columnId) {
		Button b_detalle = new Button();
		Ars ref = (Ars) itemId;
		b_detalle.addStyleName(SiarpTheme.BUTTON_PRIMARY);
		b_detalle.setIcon(FontAwesome.PRINT);
		b_detalle.setDescription("Escoja una referencia");
		b_detalle.setImmediate(true);
		b_detalle.addClickListener(e -> generarReporte(ref));
		return b_detalle;
	}
	private void generarReporte(Ars ref) {
		// REPORTE
		ReportARS report = new ReportARS(macropartesService, ref.getNcom(), "F2 - REMISION - ");
		UI.getCurrent().addWindow(report);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// panel_3
		panel_3 = buildPanel_3();
		mainLayout.addComponent(panel_3);
		
		// panel_1
		panel_1 = buildPanel_1();
		mainLayout.addComponent(panel_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_3() {
		// common part: create layout
		panel_3 = new Panel();
		panel_3.setCaption("Buscar ARS");
		panel_3.setImmediate(false);
		panel_3.setWidth("100.0%");
		panel_3.setHeight("-1px");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		panel_3.setContent(horizontalLayout_1);
		
		return panel_3;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("100.0%");
		horizontalLayout_1.setMargin(true);
		horizontalLayout_1.setSpacing(true);
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Buscar");
		horizontalLayout_1.addComponent(label_1);
		
		// tf_buscarArs
		tf_buscarArs = new TextField();
		tf_buscarArs.setImmediate(false);
		tf_buscarArs.setWidth("-1px");
		tf_buscarArs.setHeight("-1px");
		horizontalLayout_1.addComponent(tf_buscarArs);
		
		// bt_buscar
		bt_buscar = new Button();
		bt_buscar.setCaption("Buscar");
		bt_buscar.setImmediate(true);
		bt_buscar.setWidth("-1px");
		bt_buscar.setHeight("-1px");
		horizontalLayout_1.addComponent(bt_buscar);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setImmediate(false);
		panel_1.setWidth("100.0%");
		panel_1.setHeight("-1px");
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		panel_1.setContent(verticalLayout_2);
		
		return panel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(false);
		
		// table_1
		table_1 = new Table();
		table_1.setImmediate(false);
		table_1.setWidth("100.0%");
		table_1.setHeight("-1px");
		verticalLayout_2.addComponent(table_1);
		
		return verticalLayout_2;
	}

}
