package com.gci.siarp.macropartes.ui;

import java.util.Collection;
import java.util.function.Consumer;

import com.gci.siarp.api.ui.SiarpTheme;
import com.gci.siarp.macropartes.domain.Referencias;
import com.gci.siarp.macropartes.service.MacropartesService;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.server.FontAwesome;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;


@SuppressWarnings("serial")
public class buscarReferencia2 extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private Table tb_busquedaR1;
	@AutoGenerated
	private Panel panel_3;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button bt_buscar;
	@AutoGenerated
	private TextField tf_referencia;
	@AutoGenerated
	private Label label_1;
	private Collection<Referencias> listTipoNotificacionPendientes;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	private BeanItemContainer<Referencias> beanConNotificacionesPendientes;
	private MacropartesService macropartesService;
	private String referencia;
	private Consumer<Referencias> consumerReferencia;
	public buscarReferencia2(MacropartesService macropartesService,String referencia, Consumer<Referencias> consumerReferencia) {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		stylos();
		this.macropartesService = macropartesService;
		this.referencia = referencia;
		this.consumerReferencia = consumerReferencia;
		beanConNotificacionesPendientes = new BeanItemContainer<Referencias>(Referencias.class);
		tb_busquedaR1.setContainerDataSource(beanConNotificacionesPendientes);
		tb_busquedaR1.addGeneratedColumn("Acciones", this::accionesReferencias);
		tb_busquedaR1.setVisibleColumns("Acciones","referencia", "nombre", "codigo");
		tb_busquedaR1.setColumnHeaders("Detalle", "Referencia", "Nombre", "Codigo");
		llenarTablaDePendiente();
		bt_buscar.addClickListener(e->buscarReferencia1());
		bt_buscar.setImmediate(true);
		// TODO add user code here
	}
	
	private void stylos(){
		tb_busquedaR1.addStyleName(SiarpTheme.TABLE_BLUE_HEADER);
		panel_1.addStyleName(SiarpTheme.PANEL_HEADER_BLUE);
		bt_buscar.setIcon(FontAwesome.SEARCH);
		bt_buscar.addStyleName(SiarpTheme.BUTTON_PRIMARY);
	}

	private void buscarReferencia1() {
		listTipoNotificacionPendientes = macropartesService.buscarTodasLasReferencia("%"+tf_referencia.getValue()+"%");
		beanConNotificacionesPendientes.removeAllItems();
		beanConNotificacionesPendientes.addAll(listTipoNotificacionPendientes);
	}

	private void llenarTablaDePendiente() {
		listTipoNotificacionPendientes = macropartesService.buscarReferencia(referencia);
		beanConNotificacionesPendientes.removeAllItems();
		beanConNotificacionesPendientes.addAll(listTipoNotificacionPendientes);
	}
	
	public Object accionesReferencias(Table source, Object itemId, Object columnId) {
		Button b_detalle = new Button();
		Referencias ref = (Referencias) itemId;
		b_detalle.addStyleName(SiarpTheme.BUTTON_BORDERLESS_COLORED);
		b_detalle.setIcon(FontAwesome.INFO_CIRCLE);
		b_detalle.setDescription("Escoja una referencia");
		b_detalle.setImmediate(true);
		b_detalle.addClickListener(e -> cerrarVentana(ref));
		return b_detalle;
	}

	private void cerrarVentana(Referencias ref) {
		consumerReferencia.accept(ref);
	}



	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// panel_1
		panel_1 = buildPanel_1();
		mainLayout.addComponent(panel_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setCaption("Buscar Referencia");
		panel_1.setImmediate(false);
		panel_1.setWidth("100.0%");
		panel_1.setHeight("-1px");
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		panel_1.setContent(verticalLayout_2);
		
		return panel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(true);
		verticalLayout_2.setSpacing(true);
		
		// panel_3
		panel_3 = buildPanel_3();
		verticalLayout_2.addComponent(panel_3);
		
		// tb_busquedaR1
		tb_busquedaR1 = new Table();
		tb_busquedaR1.setImmediate(false);
		tb_busquedaR1.setWidth("100.0%");
		tb_busquedaR1.setHeight("-1px");
		verticalLayout_2.addComponent(tb_busquedaR1);
		
		return verticalLayout_2;
	}

	@AutoGenerated
	private Panel buildPanel_3() {
		// common part: create layout
		panel_3 = new Panel();
		panel_3.setImmediate(false);
		panel_3.setWidth("100.0%");
		panel_3.setHeight("-1px");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		panel_3.setContent(horizontalLayout_1);
		
		return panel_3;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(true);
		horizontalLayout_1.setSpacing(true);
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Referencia");
		horizontalLayout_1.addComponent(label_1);
		
		// tf_referencia
		tf_referencia = new TextField();
		tf_referencia.setImmediate(false);
		tf_referencia.setWidth("-1px");
		tf_referencia.setHeight("-1px");
		horizontalLayout_1.addComponent(tf_referencia);
		
		// bt_buscar
		bt_buscar = new Button();
		bt_buscar.setCaption("Buscar");
		bt_buscar.setImmediate(true);
		bt_buscar.setWidth("-1px");
		bt_buscar.setHeight("-1px");
		horizontalLayout_1.addComponent(bt_buscar);
		
		return horizontalLayout_1;
	}

}
